# Generated by Django 5.2.4 on 2025-08-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('user', '0002_customuser_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('change_info', 'تغییر اطلاعات گروه'), ('edit_message', 'ویرایش پیام'), ('delete_message', 'حذف پیام'), ('ban_user', 'مسدود کردن کاربر'), ('invite_user', 'دعوت کاربر'), ('pin_message', 'سنجاق پیام'), ('promote_admin', 'ترفیع به ادمین'), ('demote_admin', 'تنزل از ادمین'), ('toggle_admin', 'تغییر دسترسی ادمین')], max_length=15)),
                ('details', models.JSONField(default=dict)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_chat_id_988040_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'date', 'id'], name='chat_messag_chat_id_6c6182_idx'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs_against', to='user.customuser'),
        ),
    ]
