# Generated by Django 5.2.4 on 2025-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_blockchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
