# Generated by Django 5.2.4 on 2025-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='custom_title',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
