# Generated by Django 5.2.4 on 2025-09-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_participant_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sequence_number',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=2),
        ),
    ]
