# Generated by Django 5.2.4 on 2025-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_sequence_number_message_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_sequence',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'sequence_number')},
        ),
    ]
