# Generated by Django 5.2.4 on 2025-08-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dev_name', models.CharField(max_length=100)),
                ('count_access_token', models.IntegerField(default=2)),
            ],
        ),
    ]
