# Generated by Django 5.2.4 on 2025-08-14 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='تاریخ و زمان آخرین فعالیت کاربر', verbose_name='آخرین بازدید'),
        ),
    ]
