# Generated by Django 5.2.4 on 2025-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_blockuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_message_me',
            field=models.BooleanField(default=True),
        ),
    ]
